name: Deploy Backend

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "${{ secrets.ROOT_PASSWORD }}" | su -c "
            docker network create cem_network 2>/dev/null || true &&
            cd /var/www/html/backend_cem &&
            git checkout docker-compose.yml &&
            git pull origin develop &&
            sed -i 's|AZURE_CLIENT_SECRET=|AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}|' docker-compose.yml &&
            docker compose down &&
            docker compose up -d --build
          " root
